### Pair Numpy

In [45]:
import numpy as np

Creación y Indexación:

In [4]:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

array1d = np.random.randint(10,100,50)
print(array1d)

[34 62 95 89 20 74 68 70 28 75 23 76 73 80 70 86 65 77 97 48 85 12 27 32
 28 99 21 20 84 56 40 71 83 39 59 18 13 82 30 52 37 29 50 43 25 57 61 79
 62 14]


In [8]:
#Accede a los elementos en las posiciones múltiplos de 5

array1d[5::5]

array([74, 23, 86, 85, 99, 40, 18, 37, 57])

In [11]:
#Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

segundo_array1d = np.random.randint(1,21,30)
print(segundo_array1d)

[19 13  9  4  6  8 18 19 11 19  4  9 13 15 19 11  9  6 14  8 17  6  1  8
 17 17  5  8  9  2]


In [15]:
# Utiliza indexación para obtener los elementos en las posiciones impares.

segundo_array1d[1::2]


array([13,  4,  8, 19, 19,  9, 15, 11,  6,  8,  6,  8, 17,  8,  2])

In [43]:
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1).

lista_listas = [[1.234,2.456,3.554,4.532,5.7765,6.3325],[7.2156,8.2254,9.2548,10.3254,11.325,12.32554],[13.1516,14.4111,15.45646,16.2254,17.33665,18.1561], [12.444,14.444,45.766,67.765,23.334,54.886]]

lista_definitiva = [[round(float(x),2) for x in sublista] for sublista in lista_listas]

array2d = np.array(lista_definitiva)
print(array2d)



[[ 1.23  2.46  3.55  4.53  5.78  6.33]
 [ 7.22  8.23  9.25 10.33 11.32 12.33]
 [13.15 14.41 15.46 16.23 17.34 18.16]
 [12.44 14.44 45.77 67.77 23.33 54.89]]


In [44]:
#Accede a la última fila de la matriz. 

array2d[3]

array([12.44, 14.44, 45.77, 67.77, 23.33, 54.89])

Reshape y Transpose

In [51]:
#Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

array3d = np.random.randint(1,101,(2,3,4))


array3d_reshaped = np.reshape(array3d,(6,4), 'C')
print(array3d_reshaped)

[[23  5 89 99]
 [ 4 31 97 70]
 [75 47 58 25]
 [46 64  7 65]
 [59 78 77 80]
 [13 92 76 42]]


In [60]:
#Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

array3d_2 = np.random.randint(1,61,(3,4,5))
print(array3d_2)


array3d_reshaped_dos = np.reshape(array3d_2,(12,5), 'C')
print(array3d_reshaped_dos)

[[[20 31 54 54 26]
  [ 7  8 27 43  6]
  [14 52  2 21  6]
  [20  9 50 11 12]]

 [[25 32 54 10  6]
  [ 7 49 42 17  3]
  [38 29 45 45 41]
  [39 18 55 51 36]]

 [[18 37 36 12  6]
  [59 17 29 21  5]
  [23 36  9 58 25]
  [56 30 37  7 16]]]
[[20 31 54 54 26]
 [ 7  8 27 43  6]
 [14 52  2 21  6]
 [20  9 50 11 12]
 [25 32 54 10  6]
 [ 7 49 42 17  3]
 [38 29 45 45 41]
 [39 18 55 51 36]
 [18 37 36 12  6]
 [59 17 29 21  5]
 [23 36  9 58 25]
 [56 30 37  7 16]]
