In [3]:
import pandas as pd

In [30]:
import numpy as np

### Pair Pandas

1. ¿Qué diferencia hay entre una Serie y un DataFrame? 

La serie es una estructura de datos unimensional y el DataFrame es bidimensional (similar a una tabla de una base de datos)

In [ ]:
#2.1

valores = [4,2,6,7,11,53,22]

indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]

In [ ]:
#2.2 Crear serie: 
serie1 = pd.Series(valores, index = indices)
print(serie1)

{'lunes': 4, 'martes': 2, 'miercoles': 6, 'jueves': 7, 'viernes': 11, 'sabado': 53, 'domingo': 22}


In [ ]:
# 2.3aCrear diccionario
serie2 = pd.Series(valores, index = indices).to_dict()
print(serie1)

{'lunes': 4, 'martes': 2, 'miercoles': 6, 'jueves': 7, 'viernes': 11, 'sabado': 53, 'domingo': 22}


In [ ]:
# 2.3b Version con zip: 

diccionario = dict(zip(indices,valores))
print(diccionario)

{'lunes': 4, 'martes': 2, 'miercoles': 6, 'jueves': 7, 'viernes': 11, 'sabado': 53, 'domingo': 22}


In [ ]:
#2.4
serie_diccionario = pd.Series(diccionario)
print(serie_diccionario)

In [ ]:
#2.5 

serie_diccionario.shape

(7,)

In [ ]:
#2.6 

serie_diccionario.dtypes

dtype('int64')

In [17]:
#2.7 

serie_diccionario.size

7

In [18]:
#2.8

serie_diccionario.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [19]:
#2.9 

serie_diccionario.values

array([ 4,  2,  6,  7, 11, 53, 22])

In [20]:
#2.10

serie_diccionario["lunes"]

4

In [23]:
#2.11

serie_diccionario["lunes":"miercoles"]

lunes        4
martes       2
miercoles    6
dtype: int64

In [ ]:
#2.11
serie_diccionario.iloc[[0,6]] 

serie_diccionario.loc[["lunes", "domingo"]]

serie_diccionario["lunes"], serie_diccionario["domingo"] ##version rara 


22

In [ ]:
#3 DATAFRAMES 

array_bid = np.random.randint(0, 50, (4,3))
print(array_bid)

[[14 38 44]
 [35 28 15]
 [ 9 47 19]
 [12 23 40]]


In [ ]:
#3.1 & 3.2
df = pd.DataFrame(array_bid,columns= ["españa", "francia", "italia"])

print(df)




   españa  francia  italia
0      14       38      44
1      35       28      15
2       9       47      19
3      12       23      40


In [40]:
#3.3 

df_medallas = pd.read_csv("files/medallas.csv", index_col = 0)

df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [50]:
#3.4

df_medallas.loc["Tailandia", "Oro"]

KeyError: 'Tailandia'